language: python
python:
- '3.8'
- '3.6'
- '3.9'
install:
- pip install -r requirements.txt
- pip install -r tests/requirements.txt
- python setup.py -q install
script: nosetests --with-coverage --cover-package=btcde
after_success:
- codecov
jobs:
  include:
  - stage: Test-Release
    deploy:
    - provider: pypi
      server: https://test.pypi.org/legacy/
      user: __token__
      password:
        secure: h/wc+642BHl/T7zlgH3B5fbpp7lttVLd13yIwJoi+YAXuZiX/w5fd2uQNnr3Kh9JAaaM2ZXDpn0Xo8y7gq8pmrrQ0IMy6Df4rKUkznLXxNt3/1yLuXGPLrBESoPUM0HRqJIUBwrJuEFS4JrKaHPf018li7+/Re93MSDPKhXSaJhzVFiwmCVDpeNWptREnrfE0FqzY+dq//w+Tac/ABp+oFTQ/IVfg1atxJbxk0sErG6CAImCOYA4mxDhBeFcJC+03jRCazHmPjrDGHjktRVU2s1CcCLzO5U1/IuzXV5bSoC8Nd58wFzfZbt3uZogvqaCK9iDez6ojbPBjcXHpM+oEYxI3MQxQo6UGBCd6uhEfjKX02GLVAY5zucQujqqRVZWnWwt3BHHzfW8NF7XBp0bYDTAgmVOhBW6I+bQPmC7mJiffnhaM/V6yQINc9wdAMAePAVA7X0AkmKgD8779lvorAegzTifUQXx8uqabH3UT5uTUavMO+WH+utpYH7gKxmO5kO1L6Efut42QknNfAgmqzRqbTpGdgk8jqs0BOjNcMJ0kJeWDJeEMtiYRm64l/CPy2OC6WU2xipfVYr30r2s/LDFUHfvwvSSkiZTFhmj9PtJzjrmbIvEcd9hnYuqf19U89IKMJ2G31Z/hql0dzTJ0Rbk5ElgRvp4b0vnVwyjmp0=
      on:
        tags: false
        condition: $TRAVIS_PYTHON_VERSION = "3.8"
        all_branches: true
  - stage: Release
    deploy:
    - provider: pypi
      user: __token__
      password:
          secure: jxdITS0ouAhc0hxp/9W3qLu0KUsXM1+l4dGoSfmSTYchOVyLX79EntXJ+LdaJKpWByASjhjZ/+OZaURjuWtvxZ0PcNjt3ZbvWIJnsq0LQnIs1DdabLpRAu5ZNjcOBb7nUqI9GIUse7b4RlPEFIhd5IjUl6e60UnaHTe3P715GoeYgYgWIngDbjWThWzjxHPr5dT5VhXf8ALZpsDS9NewVSo5ogwArY+Rs1bnYn+F2OddpDZkN91tK15SD1Okwg3VtsDB5HL7NrOmtrP0sbyksBNSflaJ7WBgqTX3k58Q6JfvYQkTHrZovW2eDjap3gMGTGd1ZNJU2R1HQbml7jLJSc1Jq1YvKhxgnVUtPgAHSn6ziWMTTQsN3fs+WG1VMVuDJ3U5A8WbGt2Y9GEPDp+faSXT3MTeF0LNSNcYsSNdiVDxkgzYuAfq3IqnwYv6Ln6wz3EsgjCqE0tS6mfQ/rWF4uOB32CFL8Kz6qhjUgbSufmBIM1c7QdX/6ay/AY+EW6QjKvo0ib2XfGqe3Zf71rHPdt9BjLwd6sEriLHbB7Y2Kp4J4QcBg5w3ZzJch7uTo2Zte6rsmKlrElGfMtQTgbXRtykGlrKZaUzQdfE3pwAqZKRxVv6CXfU7gZ1lVsWVpm0NF+mOhQysdM9QFwjbrAYPdkafuimgi33Za4Ox3RCwxI=
      on:
        tags: true
        branch: master
        condition: $TRAVIS_PYTHON_VERSION = "3.8"
